<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Send feedback_gb_Ia gbii</name>
   <tag></tag>
   <elementGuidId>f260398c-9f72-4ca1-8497-224f08b491a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='gb']/div[2]/div[3]/div/div[2]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.gb_Ia.gbii</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_Ia gbii</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://lh3.googleusercontent.com/ogw/ADGmqu_grs7z7h4v6B5yqtWo-CvITqUaJ5hdC4TkGwWc=s32-c-mo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://lh3.googleusercontent.com/ogw/ADGmqu_grs7z7h4v6B5yqtWo-CvITqUaJ5hdC4TkGwWc=s32-c-mo 1x, https://lh3.googleusercontent.com/ogw/ADGmqu_grs7z7h4v6B5yqtWo-CvITqUaJ5hdC4TkGwWc=s64-c-mo 2x </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_Vd gb_fe gb_5d&quot;]/div[@class=&quot;gb_9d gb_Xa gb_Ud gb_ce&quot;]/div[@class=&quot;gb_5e&quot;]/div[@class=&quot;gb_Sa gb_gd gb_Ig gb_i gb_Wf&quot;]/div[@class=&quot;gb_Vf gb_Wa gb_Ig gb_i&quot;]/a[@class=&quot;gb_D gb_Ra gb_i&quot;]/img[@class=&quot;gb_Ia gbii&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='gb']/div[2]/div[3]/div/div[2]/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://lh3.googleusercontent.com/ogw/ADGmqu_grs7z7h4v6B5yqtWo-CvITqUaJ5hdC4TkGwWc=s32-c-mo')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
